server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10

spring:
  datasource:
    url: jdbc:h2:mem:iot;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:true}
  cache:
    type: simple

logging:
  level:
    org.springframework: WARN
    com.zaxxer.hikari: WARN
    com.example.iotbench: INFO
